export const en = {
  brand: "TrustShield AI", tagline: "Before you trust it, verify it.", simpleMode: "Simple Mode", language: "Language", menu: "Open menu", home: "Home", analyze: "Analyze", family: "Family safety", paid: "Build my case", verify: "Verify",
  heroText: "AI-powered protection against scams, impersonation, phishing, fake opportunities and digital fraud.", analyzeSuspicious: "Analyze Something Suspicious", alreadyLost: "I Already Lost Money",
  student: "Student / Job Scam", studentDesc: "Someone offered me a job or internship", familyTitle: "Family Emergency Scam", familyDesc: "Someone says they are my family member", paidTitle: "Already Paid", paidDesc: "I already sent money",
  recognize: "RECOGNIZE", recognizeDesc: "Notice warning signs", verifyStep: "VERIFY", verifyStepDesc: "Check another source", prevent: "PREVENT", preventDesc: "Pause before acting", respond: "RESPOND", respondDesc: "Protect your next step",
  trustNote: "TrustShield is a safety assistant, not law enforcement. We never ask for passwords or OTPs.",
  familyQuestion: "Someone says your family member is in trouble. What happened?", continue: "Continue", emergencyCall: "Emergency call", videoCall: "Video call", voiceMessage: "Voice message", whatsapp: "WhatsApp message", mediaSent: "Photo/video sent", moneyRequested: "Money requested",
  stopTitle: "STOP. Don't send money yet.", stopText: "Take one minute to verify through another channel.", showActions: "Show me what to do", callDirectly: "CALL THEM DIRECTLY", callGuide: "Use a number you already know, not the number in the message.", askFamily: "ASK FAMILY", askFamilyGuide: "Contact another relative who can check on them.", privateQuestion: "ASK A PRIVATE QUESTION", privateQuestionGuide: "Ask something only your real family member would know.", checkPayment: "CHECK PAYMENT", checkPaymentGuide: "Confirm the recipient name before sending anything.", aiNote: "AI-generated video or voice cannot always be identified by looking at it. Verify through another channel.", verifyFirst: "VERIFY FIRST", back: "Back",
  analysisTitle: "Check something suspicious", analysisIntro: "Paste the content exactly as you received it. Your result will appear below.", message: "Message", url: "URL", screenshot: "Screenshot", document: "Document", pasteMessage: "Paste the suspicious message here", enterUrl: "Enter the full website address", sensitiveWarning: "Do not paste passwords, OTPs, PINs or card CVV.", trySample: "Try a sample", fakeInternship: "Fake Internship", fakeBank: "Fake Bank Support", familyEmergency: "Family Emergency", recoveryScam: "Recovery Scam", legitimateInternship: "Legitimate Internship", deliveryNotification: "Delivery Notification", analyzeNow: "Analyze now", analyzing: "Checking safely…", analysisError: "We couldn't analyze that. Check the input and try again.", comingSoon: "Coming soon", uploadSoon: "File checks are being prepared. Please use Message or URL today.", howVerify: "How to verify", estimateDisclaimer: "This is an AI estimate, not proof. Verification recommended.",
  caseTitle: "Build My Case", caseIntro: "Organize what happened into a clear record you can save and share.", whatHappened: "What happened?", dateTime: "Date and time", amount: "Amount", paymentMethod: "Payment method", transactionId: "Transaction ID / UTR", recipient: "Recipient / UPI ID", phone: "Phone", email: "Email", website: "Website", social: "Social account", name: "Organization / person name", promised: "Promised service", delivered: "What was delivered", evidence: "Evidence notes", next: "Next", createCase: "Create case summary", caseSummary: "Case summary", timeline: "Timeline", copy: "Copy", copied: "Copied", download: "Download .txt", officialHelp: "Official Help", portal: "National Cyber Crime Reporting Portal", helpline: "Call the 1930 helpline", controlNote: "You stay in control. TrustShield does not report anything for you.", recoveryWarning: "If someone offers to recover your money for a fee, do not pay.",
  verifyTitle: "Verify Before You Trust", verifyIntro: "Enter an identifier to prepare it for checking.", identifier: "Phone, email, website, UPI, social URL or organization", checkIdentifier: "Check identifier", needsVerification: "Needs Verification", liveSoon: "Live checks are coming soon. For now, confirm through an official channel.", startAgain: "Start again",
  verified: "Verified", suspicious: "Suspicious", reportedIdentifier: "Reported Identifier", verifying: "Checking…", verifyError: "We couldn't check that identifier. Please try again.",
} as const;