import { createFileRoute } from "@tanstack/react-router";
import { Copy, Download, ExternalLink, PhoneCall } from "lucide-react";
import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { useI18n } from "@/i18n";
import { buildCase } from "@/lib/api";
import type { CaseData, CaseResult } from "@/types/analysis";

export const Route = createFileRoute("/paid")({ head: () => ({ meta: [{ title: "Build My Case — TrustShield AI" }, { name: "description", content: "Organize payment and contact evidence into a downloadable case summary." }, { property: "og:title", content: "Build My Case — TrustShield AI" }, { property: "og:description", content: "Create a clear record after a suspicious payment." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }] }), component: PaidPage });

const steps = [["whatHappened", "dateTime", "amount", "paymentMethod"], ["transactionId", "recipient", "phone", "email"], ["website", "social", "name", "promised"], ["delivered", "evidence"]] as const;
function PaidPage() {
  const { t } = useI18n(); const [step, setStep] = useState(0); const [data, setData] = useState<CaseData>({}); const [result, setResult] = useState<CaseResult | null>(null); const [copied, setCopied] = useState(false);
  const update = (key: string, value: string) => setData((current) => ({ ...current, [key]: value }));
  const caseText = result ? [`CASE #${result.caseId}`, `Created: ${result.createdAt}`, ...steps.flat().map((key) => `${t(key)}: ${result[key] || "—"}`)].join("\n") : "";
  async function create() { setResult(await buildCase(data)); }
  async function copy() { await navigator.clipboard.writeText(caseText); setCopied(true); window.setTimeout(() => setCopied(false), 1500); }
  function download() { const href = URL.createObjectURL(new Blob([caseText], { type: "text/plain" })); const anchor = window.document.createElement("a"); anchor.href = href; anchor.download = "TrustShield-case-TS-2026-001.txt"; anchor.click(); URL.revokeObjectURL(href); }
  if (result) return <div className="page-wrap max-w-4xl"><p className="section-kicker">{t("caseSummary")}</p><h1>CASE #{result.caseId}</h1><section className="mt-8 border border-border bg-card p-5 shadow-sm"><h2>{t("timeline")}</h2><div className="mt-5 space-y-4">{steps.flat().map((key, index) => result[key] && <div key={key} className="grid grid-cols-[2rem_1fr] gap-3 border-b border-border pb-4"><span className="font-black text-primary">{String(index + 1).padStart(2, "0")}</span><div><p className="font-bold">{t(key)}</p><p className="break-words text-muted-foreground">{result[key]}</p></div></div>)}</div><div className="mt-5 grid gap-3 sm:grid-cols-2"><Button onClick={copy} variant="outline" className="min-h-14"><Copy/>{copied ? t("copied") : t("copy")}</Button><Button onClick={download} className="min-h-14"><Download/>{t("download")}</Button></div></section><HelpSection/></div>;
  return <div className="page-wrap max-w-3xl"><p className="section-kicker">{step + 1} / {steps.length}</p><h1>{t("caseTitle")}</h1><p className="page-intro">{t("caseIntro")}</p><section className="mt-8 border border-border bg-card p-5 shadow-sm"><div className="mb-6 flex gap-2" aria-label="Progress">{steps.map((_, index) => <span key={index} className={`h-2 flex-1 ${index <= step ? "bg-primary" : "bg-border"}`}/>)}</div><div className="space-y-5">{steps[step].map((key) => <label key={key} className="block font-bold">{t(key)}{["whatHappened", "promised", "delivered", "evidence"].includes(key) ? <Textarea value={data[key] ?? ""} onChange={(event) => update(key, event.target.value)} className="mt-2 min-h-28 text-lg"/> : <Input type={key === "dateTime" ? "datetime-local" : key === "email" ? "email" : "text"} value={data[key] ?? ""} onChange={(event) => update(key, event.target.value)} className="mt-2 h-14 text-lg"/>}</label>)}</div><div className="mt-7 grid grid-cols-2 gap-3">{step > 0 ? <Button variant="outline" onClick={() => setStep(step - 1)} className="min-h-14">{t("back")}</Button> : <span/>}<Button onClick={() => step === steps.length - 1 ? create() : setStep(step + 1)} className="min-h-14">{step === steps.length - 1 ? t("createCase") : t("next")}</Button></div></section><aside className="mt-6 border-l-4 border-critical bg-critical-soft p-5 font-bold text-critical">{t("recoveryWarning")}</aside></div>;
}
function HelpSection() { const { t } = useI18n(); return <section className="mt-8"><h2>{t("officialHelp")}</h2><div className="mt-4 grid gap-3 sm:grid-cols-2"><Button asChild variant="outline" className="min-h-16 whitespace-normal"><a href="https://cybercrime.gov.in" target="_blank" rel="noreferrer">{t("portal")}<ExternalLink/></a></Button><Button asChild className="min-h-16"><a href="tel:1930"><PhoneCall/>{t("helpline")}</a></Button></div><p className="mt-4 text-center font-bold text-muted-foreground">{t("controlNote")}</p><aside className="mt-6 border-l-4 border-critical bg-critical-soft p-5 font-bold text-critical">{t("recoveryWarning")}</aside></section>; }